CREATE DATABASE quizdb;

USE quizdb;

CREATE TABLE questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    question TEXT NOT NULL,
    option1 VARCHAR(255) NOT NULL,
    option2 VARCHAR(255) NOT NULL,
    option3 VARCHAR(255) NOT NULL,
    option4 VARCHAR(255) NOT NULL,
    correct_option INT NOT NULL  -- store 1,2,3,4
);

INSERT INTO questions (question, option1, option2, option3, option4, correct_option) VALUES
("What is the capital of France?", "Berlin", "Madrid", "Paris", "Rome", 3),
("Which language runs in a web browser?", "Java", "C", "Python", "JavaScript", 4),
("Which company developed Java?", "Microsoft", "Sun Microsystems", "Google", "IBM", 2),
("What is the square root of 64?", "6", "8", "7", "9", 2),
("Which keyword is used to define a class in Java?", "define", "class", "struct", "new", 2),
("What does SQL stand for?", "Structured Query Language", "Simple Query List", "Sequential Question Language", "None", 1),
("Which symbol is used to end a statement in Java?", ".", ",", ";", ":", 3),
("Which protocol is used for sending emails?", "HTTP", "SMTP", "FTP", "POP3", 2),
("Which one is a compiled language?", "Python", "Java", "HTML", "JavaScript", 2),
("Which country invented the Zero?", "Greece", "India", "Egypt", "China", 2),
("Which data structure uses LIFO?", "Queue", "Stack", "Array", "Graph", 2),
("Which is the largest planet in our solar system?", "Earth", "Mars", "Jupiter", "Saturn", 3),
("Who is known as the father of computers?", "Charles Babbage", "Alan Turing", "Bill Gates", "Steve Jobs", 1),
("Which one is not an OOP concept?", "Inheritance", "Polymorphism", "Abstraction", "Compiling", 4),
("Which keyword is used for inheritance in Java?", "extends", "inherits", "super", "this", 1),
("Which gas do humans inhale?", "Carbon Dioxide", "Oxygen", "Nitrogen", "Hydrogen", 2),
("What is the default value of int in Java?", "0", "1", "null", "-1", 1),
("Which SQL clause is used to filter records?", "ORDER BY", "WHERE", "GROUP BY", "HAVING", 2),
("Which keyword is used to create an object in Java?", "create", "object", "new", "init", 3),
("Which operator is used for logical AND in Java?", "&", "&&", "|", "||", 2),
("Which data type is used to store true/false?", "boolean", "int", "char", "double", 1),
("What is 2 to the power 5?", "32", "64", "16", "25", 1),
("Which planet is known as the Red Planet?", "Earth", "Mars", "Venus", "Jupiter", 2),
("Which ocean is the largest?", "Atlantic", "Indian", "Pacific", "Arctic", 3),
("Which layer of Earth contains magma?", "Crust", "Mantle", "Core", "Lithosphere", 2),
("Which one is a Java IDE?", "Eclipse", "Photoshop", "Excel", "Word", 1),
("Which method is entry point in Java?", "start()", "run()", "main()", "init()", 3),
("Which SQL function is used to count rows?", "SUM()", "AVG()", "COUNT()", "MAX()", 3),
("Which organ purifies blood in humans?", "Liver", "Kidney", "Heart", "Lungs", 2),
("Which company owns GitHub?", "Google", "Microsoft", "Amazon", "Apple", 2),
("What does HTML stand for?", "HyperText Markup Language", "HighText Machine Language", "Hyperlinking Text Mark Language", "None", 1),
("Which programming language is platform-independent?", "C", "C++", "Java", "Python", 3),
("What does RAM stand for?", "Random Access Memory", "Read Access Memory", "Rapid Action Machine", "None", 1),
("Which is the smallest prime number?", "1", "2", "3", "5", 2),
("Which keyword prevents inheritance in Java?", "static", "final", "private", "abstract", 2),
("Which is the fastest land animal?", "Cheetah", "Horse", "Lion", "Tiger", 1),
("Which symbol is used for single-line comment in Java?", "//", "/*", "<!--", "#", 1),
("Which SQL keyword is used to combine tables?", "JOIN", "LINK", "COMBINE", "MERGE", 1),
("Which blood group is universal donor?", "O+", "O-", "AB+", "AB-", 2),
("Which Java package is used for GUI?", "java.util", "java.io", "javax.swing", "java.sql", 3),
("Which is the smallest continent?", "Asia", "Europe", "Australia", "Africa", 3),
("Which keyword is used to inherit interfaces in Java?", "super", "extends", "implements", "inherits", 3),
("What is the freezing point of water?", "0°C", "32°C", "100°C", "-1°C", 1),
("Which one is not a database?", "MySQL", "MongoDB", "Oracle", "HTML", 4),
("Who developed the theory of relativity?", "Newton", "Einstein", "Tesla", "Galileo", 2),
("Which unit is used to measure electric current?", "Watt", "Volt", "Ampere", "Ohm", 3),
("Which file extension is for Java class files?", ".java", ".class", ".jar", ".exe", 2),
("Which SQL statement is used to insert data?", "ADD", "INSERT INTO", "UPDATE", "CREATE", 2),
("Which country is known as the Land of Rising Sun?", "India", "China", "Japan", "Korea", 3),
("Which loop executes at least once?", "for", "while", "do-while", "foreach", 3),
("Which is the largest mammal?", "Elephant", "Blue Whale", "Shark", "Giraffe", 2);